# This is a CI workflow that runs on every push and pull request
name: CI

# Trigger the workflow on push events
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This is the job that builds and tests the code
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

