# This is a CD workflow that runs manually
name: Publish and Deploy UtiliSense to Staging 

# Trigger the workflow manually using workflow_dispatch

on: workflow_dispatch

env:
  AZURE_WEBAPP_NAME: UtiliSense


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is the job that deploys the code
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # The environment that the job references
    environment: staging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Publish the app to Azure App Service using the publish profile
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ED032E3F84BE485BA2BDD9891735EAE6 }}
          package: ${{ github.workspace }}/UtiliSense/bin/Release/net5.0/publish

